### ISSUE TITLE
Bad Window path name when attempting to add after a remove

### ISSUE THREAD

**Issue by MehsterTurdlord** [MehsterTurdlord/Automatic_Invoice#6]
```
Adding new product...
i  = 2 | n  = 0
1
Adding new product...
i  = 2 | n  = 1
2
0
-1
.!frame5.!entry
1
-1
.!frame5.!entry2
2
-1
.!frame5.!entry3
Removing last product...
1
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/ehi/Documents/GitHub/Automatic_Invoice/InvoiceWriter.py", line 149, in addProduct
    pScreens[n].grid( row = 0, column = 3, padx = 10, pady = 10, rowspan = 4, columnspan = 3 );
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2493, in grid_configure
    self.tk.call(
_tkinter.TclError: bad window path name ".!frame5"
```

**Comment by MehsterTurdlord** [comment]
I assume this is an issue with the functions calling a frame that does not exist, creating one that does, or using the wrong integer value.

**Comment by MehsterTurdlord** [comment]
```
Adding new product...
i  = 2 | n  = 0
1
[<tkinter.Frame object .!frame2>]
Adding new product...
i  = 2 | n  = 1
2
[<tkinter.Frame object .!frame2>, <tkinter.Frame object .!frame5>]
0
-1
.!frame5.!entry
1
-1
.!frame5.!entry2
2
-1
.!frame5.!entry3
Removing last product...
1
[<tkinter.Frame object .!frame2>, <tkinter.Frame object .!frame5>]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/ehi/Documents/GitHub/Automatic_Invoice/InvoiceWriter.py", line 149, in addProduct
    pScreens[n].grid( row = 0, column = 3, padx = 10, pady = 10, rowspan = 4, columnspan = 3 );
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2493, in grid_configure
    self.tk.call(
_tkinter.TclError: bad window path name ".!frame5"

```
It does not delete the frame.

**Comment by MehsterTurdlord** [comment]
I fixed this issue by not destroying the frames, but replacing them in the lists.
